### ISSUE TITLE
It keeps failing to copy data

### ISSUE THREAD

**Issue by Glitched-fra** [yechentide/AppSupport#1]
Edit: I discovered the reason and I will rectify the issue, but if I encounter further difficulties, I will return.

Edit 2: You have to press the `folder with the gear` on it next to external worlds

**Comment by yechentide** [comment]
Hello! Thanks for using my tool 😃
Are you saying you encounter error messages when you attempt to copy worlds from the Minecraft folder you've selected?

This appears to be a bug.
When users choose an external folder, a bookmark is generated.
At present, I'm unsure whether this is due to the bookmark having an expiry date, or if there's an issue with the way I'm saving bookmarks. I will make an attempt to resolve this issue.

Currently, you can normally import external worlds by resetting the external folder of the Minecraft worlds.

**Comment by Glitched-fra** [comment]
> Hello! Thanks for using my tool 😃
> 
> Are you saying you encounter error messages when you attempt to copy worlds from the Minecraft folder you've selected?
> 
> 
> 
> This appears to be a bug.
> 
> When users choose an external folder, a bookmark is generated.
> 
> At present, I'm unsure whether this is due to the bookmark having an expiry date, or if there's an issue with the way I'm saving bookmarks. I will make an attempt to resolve this issue.
> 
> 
> 
> Currently, you can normally import external worlds by resetting the external folder of the Minecraft worlds.

I figured that out lol thanks for helping
